/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 28fa85c9eb63
 */

export interface Env {
  // Add your Cloudflare Worker environment bindings here
  // For example:
  // MY_KV_NAMESPACE: KVNamespace;
  // MY_DURABLE_OBJECT: DurableObjectNamespace;
  EGAIN_EGAIN_MCP_SERVER_MCP: DurableObjectNamespace;
  ASSETS: Fetcher; // For serving static assets
}
