/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { getArticleById } from "../../funcs/getArticleById.js";
import { GetArticleByIdRequest$zodSchema } from "../../models/getarticlebyidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetArticleByIdRequest$zodSchema,
};

export const tool$getArticleById: ToolDefinition<typeof args> = {
  name: "get-article-by-id",
  description: `Get Article by ID

Get Article by ID

## How to Use This Tool

**CRITICAL**: This tool requires a \`request\` parameter containing the request object. All parameters must be passed inside a \`request\` object.

**Parameter Format**: 
- Always wrap parameters in a \`request\` object: \`{"request": {"portalID": "PZ-9999", "articleID": "PROD-2996"}}\`
- Required parameters:
  - \`portalID\` (string) - The portal ID (format: 2-4 letter prefix + dash + 4-15 digits, e.g., "PZ-9999")
  - \`articleID\` (string) - The article ID (format: 2-4 letter prefix + dash + 4-15 digits, e.g., "PROD-2996")
  - \`acceptLanguage\` (string, default: "en-US") - Accept-Language header value
- Optional parameters:
  - \`Dollar_lang\` (string, default: "en-US") - Language code
  - \`articleAdditionalAttributes\` (array) - Additional article attributes to return
  - \`Dollar_customAdditionalAttributes\` (string) - Custom additional attributes
  - \`accessSource\` (string, default: "article_view") - How the article was accessed
  - \`publishViewId\` (string) - Publish view ID
  - \`workflowMilestone\` (string) - Workflow milestone filter

**Example**: To get article "PROD-2996" from portal "PZ-9999", call with:
\`\`\`json
{"request": {"portalID": "PZ-9999", "articleID": "PROD-2996"}}
\`\`\`

**Example with optional parameters**:
\`\`\`json
{"request": {"portalID": "PZ-9999", "articleID": "PROD-2996", "Dollar_lang": "en-US", "accessSource": "article_view"}}
\`\`\`

## Displaying Results (MCP-Specific)
**CRITICAL**: When this tool returns data successfully, you MUST display the article content to the user in your response. Do not silently process the data - always show the user what was returned.

**What to display:**
- Display the article \`name\` as the title
- Show the article \`content\` or \`contentText\` (the full article body)
- Display article metadata: \`id\`, \`articleType\`, \`createdDate\`, \`modifiedDate\`
- Show \`attachments\` if present
- Display \`topicBreadcrumb\` to show where the article is categorized
- Include any other relevant metadata like \`articleSummary\`, \`description\`, \`articleKeywords\`
- Format the article content in a readable way for the user

**Example**: "Here's the article '[Article Name]' (ID: PROD-2996): [article content]. This article is categorized under: [topic breadcrumb]..."

## Prerequisites
- Requires a valid portal ID. If you don't have the portal ID, first call 'get-portals' to get available portals.
- Portal ID format: 2-4 letter prefix + dash + 4-15 digits (e.g., "EB-123456789")
- Requires a valid article ID. Article ID format: 2-4 letter prefix + dash + 4-15 digits (e.g., "PROD-2996")

## Overview
The Get Article by ID API allows a user to retrieve a specific article using its ID. Additional article attributes and contextual views can be specified in the query parameters.

This API returns structured authoring attributes of Issue, Environment, Cause and Confidence Level when the following conditions are met:
- The "Allow Structured Authoring" setting is enabled at the partition/department level
- The "Use Structured Authoring" flag is set on the article type
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await getArticleById(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
