/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { getAnnouncementArticles } from "../../funcs/getAnnouncementArticles.js";
import { GetAnnouncementArticlesRequest$zodSchema } from "../../models/getannouncementarticlesop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetAnnouncementArticlesRequest$zodSchema,
};

export const tool$getAnnouncementArticles: ToolDefinition<typeof args> = {
  name: "get-announcement-articles",
  description: `Get Announcement Articles

Get Announcements

## How to Use This Tool

**CRITICAL**: This tool requires a \`request\` parameter containing the request object. All parameters must be passed inside a \`request\` object.

**Parameter Format**: 
- Always wrap parameters in a \`request\` object: \`{"request": {"portalID": "PZ-9999"}}\`
- Required parameter:
  - \`portalID\` (string) - The portal ID (format: 2-4 letter prefix + dash + 4-15 digits, e.g., "PZ-9999")
  - \`acceptLanguage\` (string, default: "en-US") - Accept-Language header value
- Optional parameters:
  - \`Dollar_lang\` (string, default: "en-US") - Language code
  - \`Dollar_pagesize\` (number, default: 10) - Number of results per page

**Example**: To get announcements from portal "PZ-9999", call with:
\`\`\`json
{"request": {"portalID": "PZ-9999"}}
\`\`\`

**Example with optional parameters**:
\`\`\`json
{"request": {"portalID": "PZ-9999", "Dollar_lang": "en-US", "Dollar_pagesize": 20}}
\`\`\`

## Displaying Results (MCP-Specific)
**CRITICAL**: When this tool returns data successfully, you MUST display the announcement articles to the user in your response. Do not silently process the data - always show the user what was returned.

**What to display:**
- Display all announcement articles with their names and IDs
- Show the article content (\`content\` or \`contentText\`) for each announcement
- Display metadata such as \`createdDate\`, \`modifiedDate\`, \`articleSummary\`
- Show \`attachments\` if present
- Include \`paginationInfo\` if pagination is used
- Format announcements in a clear list format

**Example**: "Here are the announcements for this portal: 1) [Announcement Name] (ID: PROD-123) - [content]..."

## Prerequisites
- Requires a valid portal ID. If you don't have the portal ID, first call 'get-portals' to get available portals.
- Portal ID format: 2-4 letter prefix + dash + 4-15 digits (e.g., "PROD-1004")

## Overview
The Get Announcements API allows a user to retrieve all announcement articles for a specific portal. Announcements are special articles that are prominently displayed to users and typically contain important updates, news, or notifications.

This API returns announcement articles with their full content, metadata, and any associated attachments or links.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await getAnnouncementArticles(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
