/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { getAnnouncements } from "../../funcs/getAnnouncements.js";
import { GetAnnouncementArticlesRequest$zodSchema } from "../../models/getannouncementarticlesop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetAnnouncementArticlesRequest$zodSchema,
};

export const tool$getAnnouncements: ToolDefinition<typeof args> = {
  name: "get-announcements",
  description: `Get Announcement Articles

Get Announcements

## Prerequisites
- Requires a valid portal ID. If you don't have the portal ID, first call 'get-portals' to get available portals.
- Portal ID format: 2-4 letter prefix + dash + 4-15 digits (e.g., "EB-123456789")

## Overview
The Get Announcements API allows a user to retrieve all announcement articles for a specific portal. Announcements are special articles that are prominently displayed to users and typically contain important updates, news, or notifications.

This API returns announcement articles with their full content, metadata, and any associated attachments or links.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await getAnnouncements(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
