/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { getPopularArticles } from "../../funcs/getPopularArticles.js";
import { GetpopulararticlesRequest$zodSchema } from "../../models/getpopulararticlesop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetpopulararticlesRequest$zodSchema,
};

export const tool$getPopularArticles: ToolDefinition<typeof args> = {
  name: "get-popular-articles",
  description: `Get Popular Articles

Get Popular Articles

## Prerequisites
- Requires a valid portal ID. If you don't have the portal ID, first call 'get-portals' to get available portals.
- Portal ID format: 2-4 letter prefix + dash + 4-15 digits (e.g., "EB-123456789")

## Overview
The Popular Articles API allows a user to retrieve the most popular articles from a specific portal. Popular articles are typically determined by user engagement metrics such as views, ratings, or usage frequency.

This API returns a list of popular articles with their metadata, allowing users to discover the most relevant and frequently accessed content within the portal.
`,
  annotations: {
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await getPopularArticles(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
