/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { makeSuggestion } from "../../funcs/makeSuggestion.js";
import { MakeSuggestionRequest$zodSchema } from "../../models/makesuggestionop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: MakeSuggestionRequest$zodSchema,
};

export const tool$makeSuggestion: ToolDefinition<typeof args> = {
  name: "make-suggestion",
  description: `Make a Suggestion

Make a Suggestion

## Prerequisites
- Requires a valid portal ID. If you don't have the portal ID, first call 'get-portals' to get available portals.
- Portal ID format: 2-4 letter prefix + dash + 4-15 digits (e.g., "EB-123456789")

## Overview
The Make a Suggestion API allows users to create an Article Suggestion from within a knowledge portal. This enables users to submit feedback, request new articles, or suggest improvements to existing content.

Users can submit suggestions with details about what they're looking for, which helps content creators understand user needs and improve the knowledge base.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await makeSuggestion(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
