/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { queryAnswers } from "../../funcs/queryAnswers.js";
import { GetBestAnswerRequest$zodSchema } from "../../models/getbestanswerop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetBestAnswerRequest$zodSchema,
};

export const tool$queryAnswers: ToolDefinition<typeof args> = {
  name: "query-answers",
  description: `Generate an Answer

Get Answers

## Prerequisites
- Requires a valid portal ID. If you don't have the portal ID, first call 'get-portals' to get available portals.
- Portal ID format: 2-4 letter prefix + dash + 4-15 digits (e.g., "EB-123456789")

## Overview
The Answers API enables users to get the best answer for a user query. This API can return certified answers or generative answers along with search results, providing users with comprehensive responses to their questions.

The API leverages AI capabilities to provide intelligent answers based on the knowledge base content, making it easier for users to find the information they need quickly and accurately.

## Request Body Notes
- **channel field**: Optional. **Recommended to omit** unless specifically needed. The API works reliably without it. If you receive a 400 Bad Request error when including channel, retry the request without the channel field.
- **Required fields**: eventId and sessionId are required in the request body.
`,
  annotations: {
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await queryAnswers(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
