/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { querySearch } from "../../funcs/querySearch.js";
import { AiSearchRequest$zodSchema } from "../../models/aisearchop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: AiSearchRequest$zodSchema,
};

export const tool$querySearch: ToolDefinition<typeof args> = {
  name: "query-search",
  description: `Hybrid Search

The Search API is a hybrid search service that combines semantic understanding with keyword precision to deliver fast, contextual, and relevant results from your enterprise knowledge base. It enables secure, role-aware access to articles, FAQs, and documentation across customer, agent, and employee interfaces. Each query returns a ranked list of results with snippets, metadata, and relevance scores. <br>**This endpoint is only available for Self Service environments.**
`,
  annotations: {
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await querySearch(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
