/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { retrieveChunks } from "../../funcs/retrieveChunks.js";
import { RetrieveChunksRequest$zodSchema } from "../../models/retrievechunksop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: RetrieveChunksRequest$zodSchema,
};

export const tool$retrieveChunks: ToolDefinition<typeof args> = {
  name: "retrieve-chunks",
  description: `Retrieve Chunks

Retrieve Chunks
## Overview
The Retrieve API enables enterprises to directly access relevant content chunks from their organizational knowledge sources. It is designed for scenarios where developers want granular control over retrieved information, such as powering custom search, analytics, or retrieval-augmented generation (RAG) pipelines.
In addition to raw chunk retrieval, the API can return **Certified Answers** if it meets the 'Certified Answer' threshold score. Responses include relevance scores, metadata, and references to maintain transparency and flexibility.
By leveraging the Retrieve API, organizations can build tailored experiences while retaining confidence in the source material.

## Prerequisites
- Requires a valid portal ID. If you don't have the portal ID, first call 'get-portals' to get available portals.
- Portal ID format: 2-4 letter prefix + dash + 4-15 digits (e.g., "PROD-1004")

## How to Use This Tool
All inputs must be wrapped inside a request object. Provide a search query and language. Optional filters can be used to narrow results by tags, topics, or user profile.

**Parameter Format**: 
- Always wrap parameters in a \`request\` object: \`{"request": {"portalID": "PZ-9999", "q": "loan information", "Dollar_lang": "en-US"}}\`
- Required parameters:
  - \`portalID\` (string) - The portal ID (format: 2-4 letter prefix + dash + 4-15 digits, e.g., "PZ-9999")
  - \`q\` (string) - The search query string
  - \`Dollar_lang\` (string) - Language code (e.g., "en-US")
- Optional parameters:
  - \`dollarFilterUserProfileID\` (string) - User profile ID filter
  - \`dollarFilterTags\` (object) - Object where keys are Category Tag IDs and values are arrays of Tag IDs
  - \`dollarFilterTopicIds\` (array) - Array of topic IDs to filter by
  - \`RetrieveRequest\` (object) - Additional request body parameters:
    - \`channel\` (object) - Channel information (optional, recommended to omit)
    - \`eventId\` (string) - Event ID
    - \`sessionId\` (string) - Session ID

**Example**: To retrieve chunks for query "loan information" from portal "PZ-9999", call with:
\`\`\`json
{"request": {"portalID": "PZ-9999", "q": "loan information", "Dollar_lang": "en-US"}}
\`\`\`

**Example with RetrieveRequest body**:
\`\`\`json
{"request": {"portalID": "PZ-9999", "q": "loan information", "Dollar_lang": "en-US", "RetrieveRequest": {"eventId": "event-123", "sessionId": "session-456"}}}
\`\`\`

## Displaying Results (MCP-Specific)
**CRITICAL**: When this tool returns data successfully, you MUST display the results to the user in your response. Do not silently process the data - always show the user what was returned.

**What to display:**
Always display results. Show each article name, article ID, snippet, and relevance score. If a certified answer is returned, display it first and list its references.

**Example**: "I found 5 relevant articles about loan information: 1) [Article Name] (ID: PROD-123) - [snippet]..."
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await retrieveChunks(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
