/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { EgainMcpCore } from "../core.js";
import { encodeFormQuery, encodeSimple } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import { APIError } from "../models/errors/apierror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import {
  GetMyPortalsRequest,
  GetMyPortalsRequest$zodSchema,
  GetMyPortalsResponse,
  GetMyPortalsResponse$zodSchema,
} from "../models/getmyportalsop.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Get All Portals Accessible To User
 *
 * @remarks
 * Get All Portals Accessible to User
 *
 * ## Overview
 * The Get All Portals Accessible to User API allows a user to fetch all portals accessible to the user across all departments.
 * - If no access tags are specified for a portal, any user can access the portal.
 * - If access tags are specified for a portal, users with a user profile that allows access can access the portal. For users with multiple user profiles, the user profile that allows access does not need to be the active user profile.
 * - Global users (partition) cannot be assigned user profiles; their access is limited to portals without access restrictions.
 * - The only articles returned are associated to an Article type when the parameter “Include in browse on portals” is set to "Yes".
 * - When the `shortUrlTemplate` query parameter is provided, the API filters accessible portals according to the specified language and template name. A portal short URL specific to the `shortUrlTemplate` value is returned in the response when available. If there is no short URL for a language, the portal object returns an empty `shortURL` field.
 *
 * ## Pagination behavior (CRITICAL for AI assistants)
 *
 * **IMPORTANT**: This endpoint is paginated. When searching for a portal by name or listing portals, you MUST automatically fetch ALL pages before concluding that a portal doesn't exist.
 *
 * ### Automatic pagination is REQUIRED when:
 * - User asks to find a portal by name (e.g., "business portal", "Master portal")
 * - User requests to list or see all portals
 * - You need to resolve a natural portal name to its ID
 *
 * ### How to detect more pages exist:
 * The response includes `paginationInfo` with:
 * - `count`: Total number of items across all pages
 * - `pagenum`: Current page number
 * - `pagesize`: Items per page (default: 25)
 *
 * **Check for more pages if ANY of these are true:**
 * 1. The number of portals returned equals `pagesize` (e.g., exactly 25 portals returned)
 * 2. `paginationInfo.count > (pagenum * pagesize)` - there are more items beyond this page
 * 3. The response includes a `link` array with a `next` relation
 *
 * ### Required pagination workflow:
 * 1. Start with `$pagenum=1` and `$pagesize=25` (default)
 * 2. After receiving the response, check `paginationInfo`
 * 3. **If more pages exist** (using the checks above), automatically call this endpoint again with `$pagenum=2`, then `$pagenum=3`, etc.
 * 4. Continue incrementing `$pagenum` until:
 *    - A page returns fewer portals than `pagesize` (indicating the last page)
 *    - A page returns zero portals
 *    - `pagenum * pagesize >= paginationInfo.count` (if count represents total items)
 * 5. Merge all portals from all pages by unique portal ID
 * 6. Only then search through the complete merged list or report results to the user
 *
 * ### Example scenario:
 * If you search for "business portal" and the first page returns 25 portals but none match:
 * - DO NOT immediately tell the user the portal doesn't exist
 * - Check `paginationInfo.count` - if it's > 25, automatically fetch page 2
 * - Continue fetching until all pages are retrieved
 * - Search the complete merged list before concluding the portal doesn't exist
 *
 * This ensures reliable portal name-to-ID resolution and prevents false "not found" errors.
 */
export function getPortals(
  client$: EgainMcpCore,
  request: GetMyPortalsRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    GetMyPortalsResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  return new APIPromise($do(
    client$,
    request,
    options,
  ));
}

async function $do(
  client$: EgainMcpCore,
  request: GetMyPortalsRequest,
  options?: RequestOptions,
): Promise<
  [
    Result<
      GetMyPortalsResponse,
      | APIError
      | SDKValidationError
      | UnexpectedClientError
      | InvalidRequestError
      | RequestAbortedError
      | RequestTimeoutError
      | ConnectionError
    >,
    APICall,
  ]
> {
  const parsed$ = safeParse(
    request,
    (value$) => GetMyPortalsRequest$zodSchema.parse(value$),
    "Input validation failed",
  );
  if (!parsed$.ok) {
    return [parsed$, { status: "invalid" }];
  }
  const payload$ = parsed$.value;
  const body$ = null;
  const path$ = pathToFunc("/myportals")();
  const query$ = encodeFormQuery({
    "$lang": payload$.Dollar_lang,
    "$order": payload$.Dollar_order,
    "$pagenum": payload$.Dollar_pagenum,
    "$pagesize": payload$.Dollar_pagesize,
    "$sort": payload$.Dollar_sort,
    "department": payload$.department,
    "filterText": payload$.filterText,
    "shortUrlTemplate": payload$.shortUrlTemplate,
  });

  const headers$ = new Headers(compactMap({
    Accept: "application/json",
    "Accept-Language": encodeSimple(
      "Accept-Language",
      payload$.acceptLanguage,
      { explode: false, charEncoding: "none" },
    ),
  }));
  const securityInput = await extractSecurity(client$._options.security);
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    options: client$._options,
    baseURL: options?.serverURL ?? client$._baseURL ?? "",
    operationID: "getMyPortals",
    oAuth2Scopes: null,
    resolvedSecurity: requestSecurity,
    securitySource: client$._options.security,
    retryConfig: options?.retries
      || client$._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || [
      "429",
      "500",
      "502",
      "503",
      "504",
    ],
  };

  const requestRes = client$._createRequest(context, {
    security: requestSecurity,
    method: "GET",
    baseURL: options?.serverURL,
    path: path$,
    headers: headers$,
    query: query$,
    body: body$,
    userAgent: client$._options.userAgent,
    timeoutMs: options?.timeoutMs || client$._options.timeoutMs
      || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req$ = requestRes.value;

  const doResult = await client$._do(req$, {
    context,
    errorCodes: [],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req$ }];
  }
  const response = doResult.value;
  const responseFields$ = {
    HttpMeta: { Response: response, Request: req$ },
  };

  const [result$] = await M.match<
    GetMyPortalsResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >(
    M.json(200, GetMyPortalsResponse$zodSchema, {
      key: "AllAccessiblePortals",
    }),
    M.nil(204, GetMyPortalsResponse$zodSchema),
    M.json([400, 401, 403, 404, 406], GetMyPortalsResponse$zodSchema, {
      key: "WSErrorCommon",
    }),
    M.json(500, GetMyPortalsResponse$zodSchema, { key: "WSErrorCommon" }),
  )(response, req$, { extraFields: responseFields$ });

  return [result$, { status: "complete", request: req$, response }];
}
