/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2784dd48e82a
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { EgainMcpCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import { createRegisterTool, registerDynamicTools } from "./tools.js";
import { tool$aiSearch } from "./tools/aiSearch.js";
import { tool$getAnnouncementArticles } from "./tools/getAnnouncementArticles.js";
import { tool$getArticleById } from "./tools/getArticleById.js";
import { tool$getBestAnswer } from "./tools/getBestAnswer.js";
import { tool$getMyPortals } from "./tools/getMyPortals.js";
import { tool$getPopularArticles } from "./tools/getPopularArticles.js";
import { tool$makeSuggestion } from "./tools/makeSuggestion.js";
import { tool$retrieveChunks } from "./tools/retrieveChunks.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  dynamic?: boolean | undefined;
  scopes?: MCPScope[] | undefined;
  getSDK?: () => EgainMcpCore;
  serverURL?: string | undefined;
  security?: SDKOptions["security"] | undefined;
  server?: SDKOptions["server"] | undefined;
  API_DOMAIN?: SDKOptions["API_DOMAIN"] | undefined;
}) {
  const server = new McpServer({
    name: "EgainMcp",
    version: "1.1.1",
  });

  const getClient = deps.getSDK || (() =>
    new EgainMcpCore({
      security: deps.security,
      serverURL: deps.serverURL,
      server: deps.server,
      API_DOMAIN: deps.API_DOMAIN,
      debugLogger: deps.logger.level === "debug"
        ? {
          log: (...args) => console.log(...args),
          group: (...args) => console.group(...args),
          groupEnd: (...args) => console.groupEnd(...args),
        }
        : undefined,
    }));

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const [tool, tools, toolMap] = createRegisterTool(
    deps.logger,
    server,
    getClient,
    scopes,
    allowedTools,
    deps.dynamic,
  );
  const resource = createRegisterResource(
    deps.logger,
    server,
    getClient,
    scopes,
  );
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    getClient,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, getClient, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$getArticleById);
  tool(tool$getAnnouncementArticles);
  tool(tool$getPopularArticles);
  tool(tool$getMyPortals);
  tool(tool$aiSearch);
  tool(tool$makeSuggestion);
  tool(tool$retrieveChunks);
  tool(tool$getBestAnswer);

  if (deps.dynamic) {
    registerDynamicTools(deps.logger, server, getClient, toolMap, scopes);
  }

  return { server, tools };
}
