workflowVersion: 1.0.0
speakeasyVersion: 1.636.2
sources:
    Retrieve API:
        inputs:
            - location: egainMCP.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/egain-corporation/mcp-test/retrieve-api
targets:
    egain-mcp:
        target: mcp-typescript
        source: Retrieve API
