/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const AcceptLanguage = {
  EnUS: "en-US",
  ESES: "es-ES",
  FRFR: "fr-FR",
  ITIT: "it-IT",
  DEDE: "de-DE",
  NLNL: "nl-NL",
  PtBR: "pt-BR",
  PTPT: "pt-PT",
  DaDK: "da-DK",
  RURU: "ru-RU",
  FrCA: "fr-CA",
  ZhCN: "zh-CN",
  JaJP: "ja-JP",
  KoKR: "ko-KR",
  SvSE: "sv-SE",
} as const;
export type AcceptLanguage = ClosedEnum<typeof AcceptLanguage>;

export const AcceptLanguage$zodSchema = z.enum([
  "en-US",
  "es-ES",
  "fr-FR",
  "it-IT",
  "de-DE",
  "nl-NL",
  "pt-BR",
  "pt-PT",
  "da-DK",
  "ru-RU",
  "fr-CA",
  "zh-CN",
  "ja-JP",
  "ko-KR",
  "sv-SE",
]);
