/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Department, Department$zodSchema } from "./department.js";
import { ShortURL, ShortURL$zodSchema } from "./shorturl.js";

export type AccessiblePortal = {
  id?: string | undefined;
  name?: string | undefined;
  description?: string | undefined;
  department?: Department | undefined;
  shortURL?: Array<ShortURL> | undefined;
};

export const AccessiblePortal$zodSchema: z.ZodType<
  AccessiblePortal,
  z.ZodTypeDef,
  unknown
> = z.object({
  department: Department$zodSchema.optional(),
  description: z.string().optional(),
  id: z.string().optional(),
  name: z.string().optional(),
  shortURL: z.array(ShortURL$zodSchema).optional(),
});
