/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The language that describes the details of a resource. Resources available in different languages may differ from each other.<li>If <code>$lang</code> is not passed, then the portal's default language is used.</li><br><br>**Important**: When using this API via SDK or MCP, use the parameter name `Dollar_lang`, not `$lang` or `lang`.
 */
export const AcceptLanguage$zodSchema = z.enum([
  "en-US",
  "es-ES",
  "fr-FR",
  "it-IT",
  "de-DE",
  "nl-NL",
  "pt-BR",
  "pt-PT",
  "da-DK",
  "ru-RU",
  "fr-CA",
  "zh-CN",
  "ja-JP",
  "ko-KR",
  "sv-SE",
]).describe(
  "The language that describes the details of a resource. Resources available in different languages may differ from each other.<li>If <code>$lang</code> is not passed, then the portal's default language is used.</li><br><br>**Important**: When using this API via SDK or MCP, use the parameter name `Dollar_lang`, not `$lang` or `lang`.",
);

export type AcceptLanguage = z.infer<typeof AcceptLanguage$zodSchema>;
