/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const AcceptLanguage$zodSchema = z.enum([
  "en-US",
  "es-ES",
  "fr-FR",
  "it-IT",
  "de-DE",
  "nl-NL",
  "pt-BR",
  "pt-PT",
  "da-DK",
  "ru-RU",
  "fr-CA",
  "zh-CN",
  "ja-JP",
  "ko-KR",
  "sv-SE",
]);

export type AcceptLanguage = z.infer<typeof AcceptLanguage$zodSchema>;
