/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f62cee81256e
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Format of the source document (HTML, DOCX, PPTX or PDF).
 */
export const AdditionalSnippetsDocType = {
  Html: "HTML",
  Docx: "DOCX",
  Pdf: "PDF",
  Pptx: "PPTX",
} as const;
/**
 * Format of the source document (HTML, DOCX, PPTX or PDF).
 */
export type AdditionalSnippetsDocType = ClosedEnum<
  typeof AdditionalSnippetsDocType
>;

export const AdditionalSnippetsDocType$zodSchema = z.enum([
  "HTML",
  "DOCX",
  "PDF",
  "PPTX",
]).describe("Format of the source document (HTML, DOCX, PPTX or PDF).");

export type AdditionalSnippets = {
  id: string;
  name: string;
  docType: AdditionalSnippetsDocType;
  docName?: string | undefined;
  snippet: string;
  keywordSnippet?: string | undefined;
  relevanceScore?: number | undefined;
  normalizedScore: number;
};

export const AdditionalSnippets$zodSchema: z.ZodType<AdditionalSnippets> = z
  .object({
    docName: z.string().optional(),
    docType: AdditionalSnippetsDocType$zodSchema,
    id: z.string(),
    keywordSnippet: z.string().optional(),
    name: z.string(),
    normalizedScore: z.number(),
    relevanceScore: z.number().optional(),
    snippet: z.string(),
  });
