/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Format of the source document (HTML, DOCX, PPTX or PDF).
 */
export const AdditionalSnippetsDocType$zodSchema = z.enum([
  "HTML",
  "DOCX",
  "PDF",
  "PPTX",
]).describe("Format of the source document (HTML, DOCX, PPTX or PDF).");

export type AdditionalSnippetsDocType = z.infer<
  typeof AdditionalSnippetsDocType$zodSchema
>;

export type AdditionalSnippets = {
  id: string;
  name: string;
  docType: AdditionalSnippetsDocType;
  docName?: string | undefined;
  snippet: string;
  keywordSnippet?: string | undefined;
  relevanceScore?: number | undefined;
  normalizedScore?: number | undefined;
};

export const AdditionalSnippets$zodSchema: z.ZodType<
  AdditionalSnippets,
  z.ZodTypeDef,
  unknown
> = z.object({
  docName: z.string().optional(),
  docType: AdditionalSnippetsDocType$zodSchema,
  id: z.string(),
  keywordSnippet: z.string().optional(),
  name: z.string(),
  normalizedScore: z.number().optional(),
  relevanceScore: z.number().optional(),
  snippet: z.string(),
});
