/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AISPaginationInfo,
  AISPaginationInfo$zodSchema,
} from "./aispaginationinfo.js";
import {
  ArticleAISearchResult,
  ArticleAISearchResult$zodSchema,
} from "./articleaisearchresult.js";

/**
 * Top search results with relevance scores
 */
export type SearchResults = {
  article?: Array<ArticleAISearchResult> | undefined;
};

export const SearchResults$zodSchema: z.ZodType<
  SearchResults,
  z.ZodTypeDef,
  unknown
> = z.object({
  article: z.array(ArticleAISearchResult$zodSchema).optional(),
}).describe("Top search results with relevance scores");

export type AISearchResponse = {
  searchResults: SearchResults;
  paginationInfo?: AISPaginationInfo | undefined;
};

export const AISearchResponse$zodSchema: z.ZodType<
  AISearchResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  paginationInfo: AISPaginationInfo$zodSchema.optional(),
  searchResults: z.lazy(() => SearchResults$zodSchema),
});
