/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AISearchResponse,
  AISearchResponse$zodSchema,
} from "./aisearchresponse.js";
import {
  LanguageCodeParameter,
  LanguageCodeParameter$zodSchema,
} from "./languagecodeparameter.js";
import { WSErrorCommon, WSErrorCommon$zodSchema } from "./wserrorcommon.js";

export type AiSearchRequest = {
  q: string;
  portalID: string;
  dollarFilterUserProfileID?: string | undefined;
  Dollar_lang?: LanguageCodeParameter | undefined;
  dollarFilterTags?: { [k: string]: Array<string> } | undefined;
  dollarFilterTopicIds?: Array<string> | undefined;
  articleCustomAdditionalAttributes?: string | undefined;
  Dollar_pagenum?: number | undefined;
  Dollar_pagesize?: number | undefined;
};

export const AiSearchRequest$zodSchema: z.ZodType<
  AiSearchRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  Dollar_lang: LanguageCodeParameter$zodSchema.default("en-US"),
  Dollar_pagenum: z.number().int().default(1).describe(
    "Pagination parameter that specifies the page number of results to be returned. Used in conjunction with $pagesize.",
  ),
  Dollar_pagesize: z.number().int().default(20).describe(
    "Pagination parameter that specifies the number of results per page. Used in conjunction with $pagenum.",
  ),
  articleCustomAdditionalAttributes: z.string().describe(
    "One or more comma-separated names for article custom attributes defined by the user to be returned.",
  ).optional(),
  dollarFilterTags: z.record(z.array(z.string())).describe(
    "An object where each key is a **Category Tag ID** (numeric string),  \n"
      + "and each value is an array of **Tag IDs** for that category.\n"
      + " **Note**:\n"
      + "  - The '$filter[tags]' query parameter JSON value should be url encoded.\n"
      + "  - Some developer tools for invoking APIs may not url encode the '$filter[tags]' query parameter JSON value by default. Ensure that only url encoded values are used.\n"
      + "  - Example of JSON value: {\"BASE-40845\":[\"BASE-40849\",\"BASE-40853\"]}\n"
      + "  - Example of URL encoded value: %7B%22BASE-40845%22%3A%5B%22BASE-40849%22%2C%22BASE-40853%22%5D%7D\n"
      + "",
  ).optional(),
  dollarFilterTopicIds: z.array(z.string()).describe(
    "An array of topic IDs. It is used to restrict search results to specific topics.",
  ).optional(),
  dollarFilterUserProfileID: z.string().describe(
    "The ID of the user profile. \n"
      + "",
  ).optional(),
  portalID: z.string().describe(
    "The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.",
  ),
  q: z.string().describe(
    "The search query string. The string must be escaped as required by the URL syntax rules.",
  ),
});

export type AiSearchResponseResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  AISearchResponse?: AISearchResponse | undefined;
  WSErrorCommon?: WSErrorCommon | undefined;
};

export const AiSearchResponseResponse$zodSchema: z.ZodType<
  AiSearchResponseResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  AISearchResponse: AISearchResponse$zodSchema.optional(),
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  WSErrorCommon: WSErrorCommon$zodSchema.optional(),
});
