/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Link, Link$zodSchema } from "./link.js";

export type AISPaginationInfo = {
  count?: number | undefined;
  pagenum?: number | undefined;
  pagesize?: number | undefined;
  link?: Array<Link> | undefined;
};

export const AISPaginationInfo$zodSchema: z.ZodType<
  AISPaginationInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  count: z.number().int().default(1),
  link: z.array(Link$zodSchema).optional(),
  pagenum: z.number().int().default(1),
  pagesize: z.number().int().default(20),
});
