/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8c3e6be4ba55
 */

import * as z from "zod";
import { Link, Link$zodSchema } from "./link.js";

export type AISPaginationInfo = {
  count?: number | undefined;
  pagenum?: number | undefined;
  pagesize?: number | undefined;
  link?: Array<Link> | undefined;
};

export const AISPaginationInfo$zodSchema: z.ZodType<AISPaginationInfo> = z
  .object({
    count: z.int().default(1),
    link: z.array(Link$zodSchema).optional(),
    pagenum: z.int().default(1),
    pagesize: z.int().default(20),
  });
