/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * This schema contains the topic ID and name of the topics. This is used by TopicBreadcrumb.
 */
export type AITopicSummary = {
  id?: string | undefined;
  name?: string | undefined;
};

export const AITopicSummary$zodSchema: z.ZodType<
  AITopicSummary,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
}).describe(
  "This schema contains the topic ID and name of the topics. This is used by TopicBreadcrumb.",
);
