/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4bf6f3d207f1
 */

import * as z from "zod";
import { AITopicSummary, AITopicSummary$zodSchema } from "./aitopicsummary.js";

/**
 * This schema contains one or more TopicSummary instances.
 */
export type AITopicBreadcrumb = {
  topicSummary?: Array<AITopicSummary> | undefined;
};

export const AITopicBreadcrumb$zodSchema: z.ZodType<AITopicBreadcrumb> = z
  .object({
    topicSummary: z.array(AITopicSummary$zodSchema).optional(),
  }).describe("This schema contains one or more TopicSummary instances.");
