/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AITopicSummary, AITopicSummary$zodSchema } from "./aitopicsummary.js";

/**
 * This schema contains one or more TopicSummary instances.
 */
export type AITopicBreadcrumb = {
  topicSummary?: Array<AITopicSummary> | undefined;
};

export const AITopicBreadcrumb$zodSchema: z.ZodType<
  AITopicBreadcrumb,
  z.ZodTypeDef,
  unknown
> = z.object({
  topicSummary: z.array(AITopicSummary$zodSchema).optional(),
}).describe("This schema contains one or more TopicSummary instances.");
