/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AccessiblePortal,
  AccessiblePortal$zodSchema,
} from "./accessibleportal.js";
import { PaginationInfo, PaginationInfo$zodSchema } from "./paginationinfo.js";

/**
 * Success
 */
export type AllAccessiblePortals = {
  portal?: Array<AccessiblePortal> | undefined;
  paginationInfo?: PaginationInfo | undefined;
};

export const AllAccessiblePortals$zodSchema: z.ZodType<
  AllAccessiblePortals,
  z.ZodTypeDef,
  unknown
> = z.object({
  paginationInfo: PaginationInfo$zodSchema.optional(),
  portal: z.array(AccessiblePortal$zodSchema).optional(),
}).describe("Success");
