/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4e441b69a785
 */

import * as z from "zod";
import {
  AccessiblePortal,
  AccessiblePortal$zodSchema,
} from "./accessibleportal.js";
import { PaginationInfo, PaginationInfo$zodSchema } from "./paginationinfo.js";

/**
 * Success
 */
export type AllAccessiblePortals = {
  portal?: Array<AccessiblePortal> | undefined;
  paginationInfo?: PaginationInfo | undefined;
};

export const AllAccessiblePortals$zodSchema: z.ZodType<AllAccessiblePortals> = z
  .object({
    paginationInfo: PaginationInfo$zodSchema.optional(),
    portal: z.array(AccessiblePortal$zodSchema).optional(),
  }).describe("Success");
