/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * The channel where the query originated, e.g., directly from the portal or via a custom integration.
 */
export const AnswersRequestType = {
  Portal: "portal",
  Custom: "custom",
} as const;
/**
 * The channel where the query originated, e.g., directly from the portal or via a custom integration.
 */
export type AnswersRequestType = ClosedEnum<typeof AnswersRequestType>;

export const AnswersRequestType$zodSchema = z.enum([
  "portal",
  "custom",
]).describe(
  "The channel where the query originated, e.g., directly from the portal or via a custom integration.",
);

export type AnswersRequestChannel = {
  type?: AnswersRequestType | undefined;
  name?: string | undefined;
};

export const AnswersRequestChannel$zodSchema: z.ZodType<AnswersRequestChannel> =
  z.object({
    name: z.string().optional(),
    type: AnswersRequestType$zodSchema.default("custom"),
  });

export type AnswersRequest = {
  channel?: AnswersRequestChannel | undefined;
  eventId?: string | undefined;
  clientSessionId?: string | undefined;
  sessionId?: string | undefined;
};

export const AnswersRequest$zodSchema: z.ZodType<AnswersRequest> = z.object({
  channel: z.lazy(() => AnswersRequestChannel$zodSchema).optional(),
  clientSessionId: z.string().optional(),
  eventId: z.string().optional(),
  sessionId: z.string().optional(),
});
