/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const ArticleAdditionalAttributes = {
  ArticleMacro: "articleMacro",
  AvailabilityDate: "availabilityDate",
  AvailableEditions: "availableEditions",
  AverageRating: "averageRating",
  BookmarkStatus: "bookmarkStatus",
  Content: "content",
  ContentText: "contentText",
  Compliance: "compliance",
  TimesRated: "timesRated",
  CreatedByUserName: "createdBy.userName",
  ModifiedByUserName: "modifiedBy.userName",
  OwnedBy: "ownedBy",
  OwnedByUserName: "ownedBy.userName",
  Workflow: "workflow",
  All: "all",
} as const;
export type ArticleAdditionalAttributes = ClosedEnum<
  typeof ArticleAdditionalAttributes
>;

export const ArticleAdditionalAttributes$zodSchema = z.enum([
  "articleMacro",
  "availabilityDate",
  "availableEditions",
  "averageRating",
  "bookmarkStatus",
  "content",
  "contentText",
  "compliance",
  "timesRated",
  "createdBy.userName",
  "modifiedBy.userName",
  "ownedBy",
  "ownedBy.userName",
  "workflow",
  "all",
]);
