/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Link, Link$zodSchema } from "./link.js";

/**
 * The type of attachment.
 */
export const ArticleAttachmentType$zodSchema = z.enum([
  "INTERNAL",
  "EXTERNAL",
]).describe("The type of attachment.");

export type ArticleAttachmentType = z.infer<
  typeof ArticleAttachmentType$zodSchema
>;

export type ArticleAttachment = {
  id?: string | undefined;
  name?: string | undefined;
  size?: number | undefined;
  type?: ArticleAttachmentType | undefined;
  link?: Link | undefined;
};

export const ArticleAttachment$zodSchema: z.ZodType<
  ArticleAttachment,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  link: Link$zodSchema.optional(),
  name: z.string().optional(),
  size: z.number().int().optional(),
  type: ArticleAttachmentType$zodSchema.optional(),
});
