/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const ArticleAdditionalAttributes$zodSchema = z.enum([
  "articleMacro",
  "availabilityDate",
  "availableEditions",
  "averageRating",
  "bookmarkStatus",
  "content",
  "contentText",
  "compliance",
  "timesRated",
  "createdBy.userName",
  "modifiedBy.userName",
  "ownedBy",
  "ownedBy.userName",
  "workflow",
  "all",
]);

export type ArticleAdditionalAttributes = z.infer<
  typeof ArticleAdditionalAttributes$zodSchema
>;
