/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const ArticleResultAdditionalAttributes$zodSchema = z.enum([
  "averageRating",
  "customAttributes",
  "description",
  "articleSummary",
  "imageURL",
  "isSubscribed",
  "timesRated",
  "topicBreadcrumb",
  "ownedBy",
  "ownedBy.userName",
  "workflow",
  "compliance",
  "personalization",
  "all",
]);

export type ArticleResultAdditionalAttributes = z.infer<
  typeof ArticleResultAdditionalAttributes$zodSchema
>;
