/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 04234889df60
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  AdditionalSnippets,
  AdditionalSnippets$zodSchema,
} from "./additionalsnippets.js";
import {
  AITopicBreadcrumb,
  AITopicBreadcrumb$zodSchema,
} from "./aitopicbreadcrumb.js";
import { SchemasTags, SchemasTags$zodSchema } from "./schemastags.js";

/**
 * Format of the source document (HTML, DOCX, PPTX or PDF).
 */
export const ArticleAISearchResultDocType = {
  Html: "HTML",
  Docx: "DOCX",
  Pdf: "PDF",
  Pptx: "PPTX",
} as const;
/**
 * Format of the source document (HTML, DOCX, PPTX or PDF).
 */
export type ArticleAISearchResultDocType = ClosedEnum<
  typeof ArticleAISearchResultDocType
>;

export const ArticleAISearchResultDocType$zodSchema = z.enum([
  "HTML",
  "DOCX",
  "PDF",
  "PPTX",
]).describe("Format of the source document (HTML, DOCX, PPTX or PDF).");

/**
 * The source type.
 */
export const ArticleAISearchResultSource = {
  EGainArticle: "eGain Article",
  EGainAttachment: "eGain Attachment",
} as const;
/**
 * The source type.
 */
export type ArticleAISearchResultSource = ClosedEnum<
  typeof ArticleAISearchResultSource
>;

export const ArticleAISearchResultSource$zodSchema = z.enum([
  "eGain Article",
  "eGain Attachment",
]).describe("The source type.");

/**
 * The custom attribute's type.
 */
export const ArticleAISearchResultType = {
  String: "STRING",
  Integer: "INTEGER",
  Boolean: "BOOLEAN",
  Datetime: "DATETIME",
} as const;
/**
 * The custom attribute's type.
 */
export type ArticleAISearchResultType = ClosedEnum<
  typeof ArticleAISearchResultType
>;

export const ArticleAISearchResultType$zodSchema = z.enum([
  "STRING",
  "INTEGER",
  "BOOLEAN",
  "DATETIME",
]).describe("The custom attribute's type.");

export type ArticleAISearchResultCustomAttribute = {
  name?: string | undefined;
  value?: Array<string> | undefined;
  type?: ArticleAISearchResultType | undefined;
};

export const ArticleAISearchResultCustomAttribute$zodSchema: z.ZodType<
  ArticleAISearchResultCustomAttribute
> = z.object({
  name: z.string().optional(),
  type: ArticleAISearchResultType$zodSchema.optional(),
  value: z.array(z.string()).optional(),
});

/**
 * The type of the Article and its attributes.
 */
export type ArticleTypeAttributes = {
  typeName?: string | undefined;
  articleTypeId?: any | undefined;
};

export const ArticleTypeAttributes$zodSchema: z.ZodType<ArticleTypeAttributes> =
  z.object({
    articleTypeId: z.any().optional(),
    typeName: z.string().optional(),
  }).describe("The type of the Article and its attributes.");

/**
 * Represents a single document or snippet returned by search, along with its metadata and relevance score.
 */
export type ArticleAISearchResult = {
  id: string;
  name: string;
  docType: ArticleAISearchResultDocType;
  docName?: string | undefined;
  source: ArticleAISearchResultSource;
  customAttributes?: Array<ArticleAISearchResultCustomAttribute> | undefined;
  snippet: string;
  keywordSnippet?: string | undefined;
  additionalSnippets?: Array<AdditionalSnippets> | undefined;
  additionalSnippetCount?: number | undefined;
  contextualSummary?: string | undefined;
  modifiedDate?: string | undefined;
  headerPath?: string | undefined;
  topicBreadcrumb: Array<AITopicBreadcrumb>;
  tagCategories?: Array<SchemasTags> | undefined;
  articleTypeAttributes?: ArticleTypeAttributes | undefined;
  relevanceScore?: number | undefined;
  normalizedScore: number;
};

export const ArticleAISearchResult$zodSchema: z.ZodType<ArticleAISearchResult> =
  z.object({
    additionalSnippetCount: z.int().optional(),
    additionalSnippets: z.array(AdditionalSnippets$zodSchema).optional(),
    articleTypeAttributes: z.lazy(() => ArticleTypeAttributes$zodSchema)
      .optional(),
    contextualSummary: z.string().optional(),
    customAttributes: z.array(
      z.lazy(() => ArticleAISearchResultCustomAttribute$zodSchema),
    ).optional(),
    docName: z.string().optional(),
    docType: ArticleAISearchResultDocType$zodSchema,
    headerPath: z.string().optional(),
    id: z.string(),
    keywordSnippet: z.string().optional(),
    modifiedDate: z.string().optional(),
    name: z.string(),
    normalizedScore: z.number(),
    relevanceScore: z.number().optional(),
    snippet: z.string(),
    source: ArticleAISearchResultSource$zodSchema,
    tagCategories: z.array(SchemasTags$zodSchema).optional(),
    topicBreadcrumb: z.array(AITopicBreadcrumb$zodSchema),
  }).describe(
    "Represents a single document or snippet returned by search, along with its metadata and relevance score.",
  );
