/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c92cdfc693e7
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const ArticleResultAdditionalAttributes = {
  AverageRating: "averageRating",
  CustomAttributes: "customAttributes",
  Description: "description",
  ArticleSummary: "articleSummary",
  ImageURL: "imageURL",
  IsSubscribed: "isSubscribed",
  TimesRated: "timesRated",
  TopicBreadcrumb: "topicBreadcrumb",
  OwnedBy: "ownedBy",
  OwnedByUserName: "ownedBy.userName",
  Workflow: "workflow",
  Compliance: "compliance",
  Personalization: "personalization",
  All: "all",
} as const;
export type ArticleResultAdditionalAttributes = ClosedEnum<
  typeof ArticleResultAdditionalAttributes
>;

export const ArticleResultAdditionalAttributes$zodSchema = z.enum([
  "averageRating",
  "customAttributes",
  "description",
  "articleSummary",
  "imageURL",
  "isSubscribed",
  "timesRated",
  "topicBreadcrumb",
  "ownedBy",
  "ownedBy.userName",
  "workflow",
  "compliance",
  "personalization",
  "all",
]);
