/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Indicates the article category name.
 */
export const TypeName$zodSchema = z.enum([
  "General",
  "Guided Help",
  "Data Link",
  "PDF Content",
  "Topic Home",
  "Suggestion",
  "Virtual Assistant Action",
  "Rich Message",
  "Library Content",
]).describe("Indicates the article category name.");

export type TypeName = z.infer<typeof TypeName$zodSchema>;

/**
 * The type of the Article and its attributes.
 */
export type ArticleType = {
  articleCategoryId?: number | undefined;
  typeName?: TypeName | undefined;
  useStructuredAuthoring?: boolean | undefined;
  articleTypeId?: string | undefined;
};

export const ArticleType$zodSchema: z.ZodType<
  ArticleType,
  z.ZodTypeDef,
  unknown
> = z.object({
  articleCategoryId: z.number().int().optional(),
  articleTypeId: z.string().optional(),
  typeName: TypeName$zodSchema.optional(),
  useStructuredAuthoring: z.boolean().optional(),
}).describe("The type of the Article and its attributes.");
