/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9816a9bf6981
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { Link, Link$zodSchema } from "./link.js";

/**
 * The type of attachment.
 */
export const ArticleAttachmentType = {
  Internal: "INTERNAL",
  External: "EXTERNAL",
} as const;
/**
 * The type of attachment.
 */
export type ArticleAttachmentType = ClosedEnum<typeof ArticleAttachmentType>;

export const ArticleAttachmentType$zodSchema = z.enum([
  "INTERNAL",
  "EXTERNAL",
]).describe("The type of attachment.");

export type ArticleAttachment = {
  id?: string | undefined;
  name?: string | undefined;
  size?: number | undefined;
  type?: ArticleAttachmentType | undefined;
  link?: Link | undefined;
};

export const ArticleAttachment$zodSchema: z.ZodType<ArticleAttachment> = z
  .object({
    id: z.string().optional(),
    link: Link$zodSchema.optional(),
    name: z.string().optional(),
    size: z.int().optional(),
    type: ArticleAttachmentType$zodSchema.optional(),
  });
