/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ArticleResult, ArticleResult$zodSchema } from "./articleresult.js";
import { PaginationInfo, PaginationInfo$zodSchema } from "./paginationinfo.js";

/**
 * One or more instances of an Article result.
 */
export type ArticleResults = {
  articles?: Array<ArticleResult> | undefined;
  paginationInfo?: PaginationInfo | undefined;
};

export const ArticleResults$zodSchema: z.ZodType<
  ArticleResults,
  z.ZodTypeDef,
  unknown
> = z.object({
  articles: z.array(ArticleResult$zodSchema).optional(),
  paginationInfo: PaginationInfo$zodSchema.optional(),
}).describe("One or more instances of an Article result.");
