/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The type of the Article and its attributes.
 */
export type ArticleType = {
  articleCategoryId?: number | undefined;
  typeName?: string | undefined;
  useStructuredAuthoring?: boolean | undefined;
  articleTypeId?: string | undefined;
};

export const ArticleType$zodSchema: z.ZodType<
  ArticleType,
  z.ZodTypeDef,
  unknown
> = z.object({
  articleCategoryId: z.number().int().optional(),
  articleTypeId: z.string().optional(),
  typeName: z.string().optional(),
  useStructuredAuthoring: z.boolean().optional(),
}).describe("The type of the Article and its attributes.");
