/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ArticleType, ArticleType$zodSchema } from "./articletype.js";
import {
  ComplianceForArticle,
  ComplianceForArticle$zodSchema,
} from "./complianceforarticle.js";
import { CreatedBy, CreatedBy$zodSchema } from "./createdby.js";
import {
  CustomAttribute,
  CustomAttribute$zodSchema,
} from "./customattribute.js";
import { LanguageCode, LanguageCode$zodSchema } from "./languagecode.js";
import { Link, Link$zodSchema } from "./link.js";
import { ModifiedBy, ModifiedBy$zodSchema } from "./modifiedby.js";
import { OwnedBy, OwnedBy$zodSchema } from "./ownedby.js";
import {
  Personalization,
  Personalization$zodSchema,
} from "./personalization.js";
import {
  TopicBreadcrumb,
  TopicBreadcrumb$zodSchema,
} from "./topicbreadcrumb.js";
import { Workflow, Workflow$zodSchema } from "./workflow.js";

/**
 * Article search result, a subset of Article that does not contain content and contentText.
 */
export type ArticleResult = {
  id?: string | undefined;
  articleType?: ArticleType | undefined;
  articleKeywords?: string | undefined;
  articleSummary?: string | undefined;
  averageRating?: number | undefined;
  createdBy?: CreatedBy | undefined;
  modifiedBy?: ModifiedBy | undefined;
  ownedBy?: OwnedBy | undefined;
  createdDate?: string | undefined;
  customAttributes?: Array<CustomAttribute> | undefined;
  description?: string | undefined;
  hasAttachments?: boolean | undefined;
  isSubscribed?: boolean | undefined;
  modifiedDate?: string | undefined;
  languageCode?: LanguageCode | undefined;
  link?: Link | undefined;
  imageURL?: string | undefined;
  name?: string | undefined;
  timesRated?: number | undefined;
  topicBreadcrumb?: Array<TopicBreadcrumb> | undefined;
  versionId?: string | undefined;
  workflow?: Workflow | undefined;
  compliance?: ComplianceForArticle | undefined;
  personalization?: Personalization | undefined;
};

export const ArticleResult$zodSchema: z.ZodType<
  ArticleResult,
  z.ZodTypeDef,
  unknown
> = z.object({
  articleKeywords: z.string().optional(),
  articleSummary: z.string().optional(),
  articleType: ArticleType$zodSchema.optional(),
  averageRating: z.number().optional(),
  compliance: ComplianceForArticle$zodSchema.optional(),
  createdBy: CreatedBy$zodSchema.optional(),
  createdDate: z.string().optional(),
  customAttributes: z.array(CustomAttribute$zodSchema).optional(),
  description: z.string().optional(),
  hasAttachments: z.boolean().optional(),
  id: z.string().optional(),
  imageURL: z.string().optional(),
  isSubscribed: z.boolean().optional(),
  languageCode: LanguageCode$zodSchema.optional(),
  link: Link$zodSchema.optional(),
  modifiedBy: ModifiedBy$zodSchema.optional(),
  modifiedDate: z.string().optional(),
  name: z.string().optional(),
  ownedBy: OwnedBy$zodSchema.optional(),
  personalization: Personalization$zodSchema.optional(),
  timesRated: z.number().int().optional(),
  topicBreadcrumb: z.array(TopicBreadcrumb$zodSchema).optional(),
  versionId: z.string().optional(),
  workflow: Workflow$zodSchema.optional(),
}).describe(
  "Article search result, a subset of Article that does not contain content and contentText.",
);
