/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * This schema contains the definition of an Attachment.
 */
export type AttachmentForCreateSuggestion = { altId?: string | undefined };

export const AttachmentForCreateSuggestion$zodSchema: z.ZodType<
  AttachmentForCreateSuggestion,
  z.ZodTypeDef,
  unknown
> = z.object({
  altId: z.string().optional(),
}).describe("This schema contains the definition of an Attachment.");
