/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  FolderBreadcrumb,
  FolderBreadcrumb$zodSchema,
} from "./folderbreadcrumb.js";

/**
 * Article Bookmark Status
 */
export type BookmarkStatus = {
  isBookmarked: boolean;
  bookmarkID?: number | undefined;
  folderBreadcrumb?: FolderBreadcrumb | undefined;
};

export const BookmarkStatus$zodSchema: z.ZodType<
  BookmarkStatus,
  z.ZodTypeDef,
  unknown
> = z.object({
  bookmarkID: z.number().int().optional(),
  folderBreadcrumb: FolderBreadcrumb$zodSchema.optional(),
  isBookmarked: z.boolean(),
}).describe("Article Bookmark Status");
