/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  AttachmentForCreateSuggestion,
  AttachmentForCreateSuggestion$zodSchema,
} from "./attachmentforcreatesuggestion.js";
import {
  CustomAttribute,
  CustomAttribute$zodSchema,
} from "./customattribute.js";

/**
 * The Article that the Suggestion was created for.
 */
export type RelatedArticleForCreateUpdateDeleteSuggestion = {
  id?: string | undefined;
};

export const RelatedArticleForCreateUpdateDeleteSuggestion$zodSchema: z.ZodType<
  RelatedArticleForCreateUpdateDeleteSuggestion
> = z.object({
  id: z.string().optional(),
}).describe("The Article that the Suggestion was created for.");

/**
 * Details of Attachments for the Suggestion.
 */
export type Attachments = {
  attachment?: Array<AttachmentForCreateSuggestion> | undefined;
};

export const Attachments$zodSchema: z.ZodType<Attachments> = z.object({
  attachment: z.array(AttachmentForCreateSuggestion$zodSchema).optional(),
}).describe("Details of Attachments for the Suggestion.");

/**
 * The code of the language.
 */
export const Code = {
  EnUS: "en-US",
  EnGB: "en-GB",
  FRFR: "fr-FR",
  ESES: "es-ES",
  ITIT: "it-IT",
  DEDE: "de-DE",
  NLNL: "nl-NL",
  PtBR: "pt-BR",
  PTPT: "pt-PT",
  DaDK: "da-DK",
  SvSE: "sv-SE",
  RURU: "ru-RU",
  ZhCN: "zh-CN",
  JaJP: "ja-JP",
  KoKR: "ko-KR",
  DeAT: "de-AT",
  THTH: "th-TH",
  ViVN: "vi-VN",
  IDID: "id-ID",
  MsMY: "ms-MY",
  FilPH: "fil-PH",
  FrCA: "fr-CA",
  HiIN: "hi-IN",
  UkUA: "uk-UA",
  BGBG: "bg-BG",
  SKSK: "sk-SK",
  SlSI: "sl-SI",
  SrRS: "sr-RS",
} as const;
/**
 * The code of the language.
 */
export type Code = ClosedEnum<typeof Code>;

export const Code$zodSchema = z.enum([
  "en-US",
  "en-GB",
  "fr-FR",
  "es-ES",
  "it-IT",
  "de-DE",
  "nl-NL",
  "pt-BR",
  "pt-PT",
  "da-DK",
  "sv-SE",
  "ru-RU",
  "zh-CN",
  "ja-JP",
  "ko-KR",
  "de-AT",
  "th-TH",
  "vi-VN",
  "id-ID",
  "ms-MY",
  "fil-PH",
  "fr-CA",
  "hi-IN",
  "uk-UA",
  "bg-BG",
  "sk-SK",
  "sl-SI",
  "sr-RS",
]).describe("The code of the language.");

/**
 * The knowledge base language in which the Suggestion is created.
 */
export type Language = { code: Code };

export const Language$zodSchema: z.ZodType<Language> = z.object({
  code: Code$zodSchema,
}).describe("The knowledge base language in which the Suggestion is created.");

/**
 * This schema contains information about a Suggestion.
 */
export type CreateSuggestion = {
  name: string;
  description?: string | undefined;
  content: string;
  feedbackArticle?: RelatedArticleForCreateUpdateDeleteSuggestion | undefined;
  attachments?: Attachments | undefined;
  language: Language;
  customAttributes?: Array<CustomAttribute> | undefined;
};

export const CreateSuggestion$zodSchema: z.ZodType<CreateSuggestion> = z.object(
  {
    attachments: z.lazy(() => Attachments$zodSchema).optional(),
    content: z.string(),
    customAttributes: z.array(CustomAttribute$zodSchema).optional(),
    description: z.string().optional(),
    feedbackArticle: z.lazy(() =>
      RelatedArticleForCreateUpdateDeleteSuggestion$zodSchema
    ).optional(),
    language: z.lazy(() => Language$zodSchema),
    name: z.string(),
  },
).describe("This schema contains information about a Suggestion.");
