/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The custom attribute's type.
 */
export const CustomAttributeType$zodSchema = z.enum([
  "STRING",
  "INTEGER",
  "BOOLEAN",
  "DATETIME",
]).describe("The custom attribute's type.");

export type CustomAttributeType = z.infer<typeof CustomAttributeType$zodSchema>;

export type CustomAttribute = {
  name?: string | undefined;
  value?: Array<string> | undefined;
  type?: CustomAttributeType | undefined;
};

export const CustomAttribute$zodSchema: z.ZodType<
  CustomAttribute,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  type: CustomAttributeType$zodSchema.optional(),
  value: z.array(z.string()).optional(),
});
