/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5524c0a23aba
 */

import * as z from "zod";

export type Department = { id?: string | undefined; name?: string | undefined };

export const Department$zodSchema: z.ZodType<Department> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
});
