/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Link, Link$zodSchema } from "./link.js";

/**
 * The publish view associated with this edition.
 */
export type PublishProfile = { id: string; name: string };

export const PublishProfile$zodSchema: z.ZodType<
  PublishProfile,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  name: z.string(),
}).describe("The publish view associated with this edition.");

/**
 * This schema contains information about an article edition.
 */
export type Edition = {
  id?: string | undefined;
  name?: string | undefined;
  isContentEdition?: boolean | undefined;
  publishProfile?: PublishProfile | undefined;
  link?: Link | undefined;
};

export const Edition$zodSchema: z.ZodType<Edition, z.ZodTypeDef, unknown> = z
  .object({
    id: z.string().optional(),
    isContentEdition: z.boolean().optional(),
    link: Link$zodSchema.optional(),
    name: z.string().optional(),
    publishProfile: z.lazy(() => PublishProfile$zodSchema).optional(),
  }).describe("This schema contains information about an article edition.");
