/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ad3d2395790f
 */

import * as z from "zod";
import { SchemasLink, SchemasLink$zodSchema } from "./schemaslink.js";

/**
 * This schema contains the topic ID and name of the Folder. This is used by FolderBreadcrumb.
 */
export type FolderSummary = {
  id?: number | undefined;
  name?: string | undefined;
  link?: SchemasLink | undefined;
};

export const FolderSummary$zodSchema: z.ZodType<FolderSummary> = z.object({
  id: z.int().optional(),
  link: SchemasLink$zodSchema.optional(),
  name: z.string().optional(),
}).describe(
  "This schema contains the topic ID and name of the Folder. This is used by FolderBreadcrumb.",
);
