/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d7a8c676107f
 */

import * as z from "zod";
import { FolderSummary, FolderSummary$zodSchema } from "./foldersummary.js";

/**
 * This schema contains one or more FolderSummary instances.
 */
export type FolderBreadcrumb = {
  folderSummary?: Array<FolderSummary> | undefined;
};

export const FolderBreadcrumb$zodSchema: z.ZodType<FolderBreadcrumb> = z.object(
  {
    folderSummary: z.array(FolderSummary$zodSchema).optional(),
  },
).describe("This schema contains one or more FolderSummary instances.");
