/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AcceptLanguage, AcceptLanguage$zodSchema } from "./acceptlanguage.js";
import {
  ArticleResultAdditionalAttributes,
  ArticleResultAdditionalAttributes$zodSchema,
} from "./articleresultadditionalattributes.js";
import { ArticleResults, ArticleResults$zodSchema } from "./articleresults.js";
import {
  LanguageQueryParameter,
  LanguageQueryParameter$zodSchema,
} from "./languagequeryparameter.js";
import { WSErrorCommon, WSErrorCommon$zodSchema } from "./wserrorcommon.js";

export type GetpopulararticlesRequest = {
  acceptLanguage?: AcceptLanguage | undefined;
  xExtIntegrationId?: string | undefined;
  xEgainActivityId?: string | undefined;
  xExtInteractionId?: string | undefined;
  portalID: string;
  dollarFilterTopicId?: string | undefined;
  Dollar_lang?: LanguageQueryParameter | undefined;
  dollarFilterTags?: string | undefined;
  Dollar_pagenum?: number | undefined;
  Dollar_pagesize?: number | undefined;
  articleResultAdditionalAttributes?:
    | Array<ArticleResultAdditionalAttributes>
    | undefined;
};

export const GetpopulararticlesRequest$zodSchema: z.ZodType<
  GetpopulararticlesRequest
> = z.object({
  Dollar_lang: LanguageQueryParameter$zodSchema.optional(),
  Dollar_pagenum: z.int().default(1).describe(
    "Pagination parameter that specifies the page number of results to be returned. Used in conjunction with $pagesize.",
  ),
  Dollar_pagesize: z.int().default(10).describe(
    "Pagination parameter that specifies the number of results per page. Used in conjunction with $pagenum.",
  ),
  acceptLanguage: AcceptLanguage$zodSchema.default("en-US"),
  articleResultAdditionalAttributes: z.array(
    ArticleResultAdditionalAttributes$zodSchema,
  ).describe(
    "The attributes of an Article to be returned *in addition to* the default list of attributes, listed below. Multiple additional attributes can be specified using a comma-separated list. Passing 'all' will return all attributes.\n\n#### Default Attributes\nThese Article attributes are always returned:\n\n| Name | Description \n| ---- | -----------\n| id | The ID of the Article.\n| name  | The name of the Article.\n| articleType | The Article Type and its attributes.\n| createdBy | The ID, first name, middle name and last name of the user that created the Article.\n| createdDate | The date that the Article was created.\n| hasAttachments | True: The Article has one or more attachments.<br>False: The Article does not have any attachments.\n| languageCode | The language code of the Article language. \n| modifiedBy | The ID, first name, middle name and last name of the user that last modified the Article.\n| modifiedDate | The date that the Article was last modified on.\n| link | The link object, used to retrieve the details of the Article.\n| versionId | The ID of the Article version that is returned.\n",
  ).optional(),
  dollarFilterTags: z.string().describe(
    "A comma separated list of Tag / Tag Group IDs. The query results will be filtered by the tags that are specified.<br><br>Tag IDs and Tag Group IDs can be mixed together.",
  ).optional(),
  dollarFilterTopicId: z.string().describe(
    "The ID of the topic. It is used to restrict to a specific topic.",
  ).optional(),
  portalID: z.string().describe(
    "The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.",
  ),
  xEgainActivityId: z.string().describe(
    "A unique numeric interaction identifier from eGain.",
  ).optional(),
  xExtIntegrationId: z.string().describe(
    "The unique numeric identifier for a tenant, used in self-service functionality as well as third-party integrations.<br><br>*Note: If x-egain-activity-id is not provided, then this must be passed along with x-ext-interaction-id.*",
  ).optional(),
  xExtInteractionId: z.string().describe(
    "A unique interaction identifier from other CRM applications.<br><br>*Note: If x-egain-activity-id is not provided, then this must be passed along with x-ext-integration-id.*",
  ).optional(),
});

export type GetpopulararticlesResponse = WSErrorCommon | ArticleResults;

export const GetpopulararticlesResponse$zodSchema: z.ZodType<
  GetpopulararticlesResponse
> = z.union([
  WSErrorCommon$zodSchema,
  ArticleResults$zodSchema,
]);
