/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type L10NString = {
  value?: string | undefined;
  displayValue?: string | undefined;
};

export const L10NString$zodSchema: z.ZodType<
  L10NString,
  z.ZodTypeDef,
  unknown
> = z.object({
  displayValue: z.string().optional(),
  value: z.string().optional(),
});
