/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d33e710b0935
 */

import * as z from "zod";

export type L10NString = {
  value?: string | undefined;
  displayValue?: string | undefined;
};

export const L10NString$zodSchema: z.ZodType<L10NString> = z.object({
  displayValue: z.string().optional(),
  value: z.string().optional(),
});
