/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Language code of the resource's language.
 */
export const LanguageCode$zodSchema = z.enum([
  "en-US",
  "fr-FR",
  "en-GB",
  "es-ES",
  "it-IT",
  "nl-NL",
  "da-DA",
  "sv-SE",
  "pt-PT",
  "fi-FI",
  "no-NB",
  "no-NN",
  "ja-JA",
  "de-DE",
  "pt-BR",
  "zh-CN",
  "zh-TW",
  "ko-KO",
  "ru-RU",
  "el-EL",
  "tr-TR",
  "pl-PL",
  "cs-CS",
  "sk-SK",
  "hu-HU",
  "sr-SR",
  "ar-SA",
  "hr-HR",
  "ro-RO",
  "th-TH",
]).describe("Language code of the resource's language.");

export type LanguageCode = z.infer<typeof LanguageCode$zodSchema>;
