/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 98b5466ecfd3
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Language code of the resource's language.
 */
export const LanguageCode = {
  EnUS: "en-US",
  FRFR: "fr-FR",
  EnGB: "en-GB",
  ESES: "es-ES",
  ITIT: "it-IT",
  NLNL: "nl-NL",
  DADA: "da-DA",
  SvSE: "sv-SE",
  PTPT: "pt-PT",
  FIFI: "fi-FI",
  NoNB: "no-NB",
  NoNN: "no-NN",
  JAJA: "ja-JA",
  DEDE: "de-DE",
  PtBR: "pt-BR",
  ZhCN: "zh-CN",
  ZhTW: "zh-TW",
  KOKO: "ko-KO",
  RURU: "ru-RU",
  ELEL: "el-EL",
  TRTR: "tr-TR",
  PLPL: "pl-PL",
  CSCS: "cs-CS",
  SKSK: "sk-SK",
  HUHU: "hu-HU",
  SRSR: "sr-SR",
  ArSA: "ar-SA",
  HRHR: "hr-HR",
  RORO: "ro-RO",
  THTH: "th-TH",
} as const;
/**
 * Language code of the resource's language.
 */
export type LanguageCode = ClosedEnum<typeof LanguageCode>;

export const LanguageCode$zodSchema = z.enum([
  "en-US",
  "fr-FR",
  "en-GB",
  "es-ES",
  "it-IT",
  "nl-NL",
  "da-DA",
  "sv-SE",
  "pt-PT",
  "fi-FI",
  "no-NB",
  "no-NN",
  "ja-JA",
  "de-DE",
  "pt-BR",
  "zh-CN",
  "zh-TW",
  "ko-KO",
  "ru-RU",
  "el-EL",
  "tr-TR",
  "pl-PL",
  "cs-CS",
  "sk-SK",
  "hu-HU",
  "sr-SR",
  "ar-SA",
  "hr-HR",
  "ro-RO",
  "th-TH",
]).describe("Language code of the resource's language.");
