/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The language that describes the details of a resource. Resources available in different languages may differ from each other.<li>If <code>$lang</code> is not passed, then the portal's default language is used.</li><br><br>**Important**: When using this API via SDK or MCP, use the parameter name `Dollar_lang`, not `$lang` or `lang`.
 */
export const LanguageQueryParameter$zodSchema = z.enum([
  "en-US",
  "fr-FR",
  "en-GB",
  "es-ES",
  "it-IT",
  "nl-NL",
  "da-DA",
  "sv-SE",
  "pt-PT",
  "fi-FI",
  "no-NB",
  "no-NN",
  "ja-JA",
  "de-DE",
  "pt-BR",
  "zh-CN",
  "zh-TW",
  "ko-KO",
  "ru-RU",
  "el-EL",
  "tr-TR",
  "pl-PL",
  "cs-CS",
  "sk-SK",
  "hu-HU",
  "sr-SR",
  "ar-SA",
  "hr-HR",
  "ro-RO",
  "th-TH",
  "de-AT",
  "vi-VN",
  "id-ID",
  "ms-MY",
  "fil-PH",
  "fr-CA",
  "hi-IN",
  "uk-UA",
  "bg-BG",
  "sl-SI",
  "sr-RS",
  "xx-XX",
]).describe(
  "The language that describes the details of a resource. Resources available in different languages may differ from each other.<li>If <code>$lang</code> is not passed, then the portal's default language is used.</li><br><br>**Important**: When using this API via SDK or MCP, use the parameter name `Dollar_lang`, not `$lang` or `lang`.",
);

export type LanguageQueryParameter = z.infer<
  typeof LanguageQueryParameter$zodSchema
>;
