/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5fc171e095d8
 */

import * as z from "zod";

/**
 * Defines the relationship between this resource and another object.
 */
export type Link = { rel?: string | undefined; href?: string | undefined };

export const Link$zodSchema: z.ZodType<Link> = z.object({
  href: z.string().optional(),
  rel: z.string().optional(),
}).describe(
  "Defines the relationship between this resource and another object.",
);
