/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 14ca86c60315
 */

import * as z from "zod";
import { AcceptLanguage, AcceptLanguage$zodSchema } from "./acceptlanguage.js";
import {
  CreateSuggestion,
  CreateSuggestion$zodSchema,
} from "./createsuggestion.js";

export type MakeSuggestionRequest = {
  xEgainActivityId?: string | undefined;
  xExtIntegrationId?: string | undefined;
  xExtInteractionId?: string | undefined;
  acceptLanguage: AcceptLanguage;
  portalID: string;
  CreateSuggestion?: CreateSuggestion | undefined;
};

export const MakeSuggestionRequest$zodSchema: z.ZodType<MakeSuggestionRequest> =
  z.object({
    CreateSuggestion: CreateSuggestion$zodSchema.optional(),
    acceptLanguage: AcceptLanguage$zodSchema,
    portalID: z.string().describe(
      "The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.",
    ),
    xEgainActivityId: z.string().describe(
      "A unique numeric interaction identifier from eGain.",
    ).optional(),
    xExtIntegrationId: z.string().describe(
      "The unique numeric identifier for a tenant, used in self-service functionality as well as third-party integrations.<br><br>*Note: The x-ext-integration-id and x-ext-interaction-id headers must always be provided together and cannot be supplied independently.<br><br>The x-egain-activity-id may be provided on its own, or it may be provided along with both x-ext-integration-id and x-ext-interaction-id.*",
    ).optional(),
    xExtInteractionId: z.string().describe(
      "A unique interaction identifier from other CRM applications.<br><br>*Note: The x-ext-integration-id and x-ext-interaction-id headers must always be provided together and cannot be supplied independently.<br><br>The x-egain-activity-id may be provided on its own, or it may be provided along with both x-ext-integration-id and x-ext-interaction-id.*",
    ).optional(),
  });
