/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The language used for fetching the details of a resource. Resources available in different languages may differ from each other. **Important**: When using this API via SDK or MCP, use the parameter name `Dollar_lang`, not `$lang` or `lang`.
 */
export const MandatoryLanguageQueryParameter$zodSchema = z.enum([
  "en-US",
  "fr-FR",
  "en-GB",
  "es-ES",
  "it-IT",
  "nl-NL",
  "da-DA",
  "sv-SE",
  "pt-PT",
  "fi-FI",
  "no-NB",
  "no-NN",
  "ja-JA",
  "de-DE",
  "pt-BR",
  "zh-CN",
  "zh-TW",
  "ko-KO",
  "ru-RU",
  "el-EL",
  "tr-TR",
  "pl-PL",
  "cs-CS",
  "sk-SK",
  "hu-HU",
  "sr-SR",
  "ar-SA",
  "hr-HR",
  "ro-RO",
  "th-TH",
]).describe(
  "The language used for fetching the details of a resource. Resources available in different languages may differ from each other. **Important**: When using this API via SDK or MCP, use the parameter name `Dollar_lang`, not `$lang` or `lang`.",
);

export type MandatoryLanguageQueryParameter = z.infer<
  typeof MandatoryLanguageQueryParameter$zodSchema
>;
