/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The identifiers of the milestone.
 */
export type MilestoneName = {
  value?: string | undefined;
  displayValue?: string | undefined;
};

export const MilestoneName$zodSchema: z.ZodType<
  MilestoneName,
  z.ZodTypeDef,
  unknown
> = z.object({
  displayValue: z.string().optional(),
  value: z.string().optional(),
}).describe("The identifiers of the milestone.");
