/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { MilestoneName, MilestoneName$zodSchema } from "./milestonename.js";

/**
 * A resource's workflow milestone.
 */
export type Milestone = { name?: MilestoneName | undefined };

export const Milestone$zodSchema: z.ZodType<Milestone, z.ZodTypeDef, unknown> =
  z.object({
    name: MilestoneName$zodSchema.optional(),
  }).describe("A resource's workflow milestone.");
