/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8ebfc9e4c369
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const Order = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type Order = ClosedEnum<typeof Order>;

export const Order$zodSchema = z.enum([
  "asc",
  "desc",
]);
