/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const Order$zodSchema = z.enum([
  "asc",
  "desc",
]);

export type Order = z.infer<typeof Order$zodSchema>;
