/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type OwnedBy = {
  id?: string | undefined;
  userName?: string | undefined;
  firstName?: string | undefined;
  middleName?: string | undefined;
  lastName?: string | undefined;
};

export const OwnedBy$zodSchema: z.ZodType<OwnedBy, z.ZodTypeDef, unknown> = z
  .object({
    firstName: z.string().optional(),
    id: z.string().optional(),
    lastName: z.string().optional(),
    middleName: z.string().optional(),
    userName: z.string().optional(),
  });
