/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Link, Link$zodSchema } from "./link.js";

export type PaginationInfo = {
  count: number;
  pagenum: number;
  pagesize: number;
  link?: Array<Link> | undefined;
};

export const PaginationInfo$zodSchema: z.ZodType<PaginationInfo> = z.object({
  count: z.int(),
  link: z.array(Link$zodSchema).optional(),
  pagenum: z.int(),
  pagesize: z.int(),
});
