/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  LanguageCodeParameter,
  LanguageCodeParameter$zodSchema,
} from "./languagecodeparameter.js";
import {
  RetrieveRequest,
  RetrieveRequest$zodSchema,
} from "./retrieverequest.js";
import {
  RetrieveResponse,
  RetrieveResponse$zodSchema,
} from "./retrieveresponse.js";
import { WSErrorCommon, WSErrorCommon$zodSchema } from "./wserrorcommon.js";

export type PostPortalIDRetrieveRequest = {
  q: string;
  portalID: string;
  dollarFilterUserProfileID?: string | undefined;
  Dollar_lang?: LanguageCodeParameter | undefined;
  dollarFilterTags?: { [k: string]: Array<string> } | undefined;
  dollarFilterTopicIds?: Array<string> | undefined;
  RetrieveRequest?: RetrieveRequest | undefined;
};

export const PostPortalIDRetrieveRequest$zodSchema: z.ZodType<
  PostPortalIDRetrieveRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  Dollar_lang: LanguageCodeParameter$zodSchema.default("en-US"),
  RetrieveRequest: RetrieveRequest$zodSchema.optional(),
  dollarFilterTags: z.record(z.array(z.string())).describe(
    "An object where each key is a **Category Tag ID** (numeric string),  \n"
      + "and each value is an array of **Tag IDs** for that category.\n"
      + "",
  ).optional(),
  dollarFilterTopicIds: z.array(z.string()).optional(),
  dollarFilterUserProfileID: z.string().optional(),
  portalID: z.string().describe(
    "The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.",
  ),
  q: z.string().describe("The search query string."),
});

export type PostPortalIDRetrieveResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  RetrieveResponse?: RetrieveResponse | undefined;
  WSErrorCommon?: WSErrorCommon | undefined;
};

export const PostPortalIDRetrieveResponse$zodSchema: z.ZodType<
  PostPortalIDRetrieveResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  RetrieveResponse: RetrieveResponse$zodSchema.optional(),
  StatusCode: z.number().int(),
  WSErrorCommon: WSErrorCommon$zodSchema.optional(),
});
