/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: cae3f9d6fcdc
 */

import * as z from "zod";
import { TagCategory, TagCategory$zodSchema } from "./tagcategory.js";

export type PublishViewTagCategory = {
  tagCategory?: Array<TagCategory> | undefined;
};

export const PublishViewTagCategory$zodSchema: z.ZodType<
  PublishViewTagCategory
> = z.object({
  tagCategory: z.array(TagCategory$zodSchema).optional(),
});

export type PublishView = {
  name?: string | undefined;
  id?: string | undefined;
  tagCategories?: Array<PublishViewTagCategory> | undefined;
};

export const PublishView$zodSchema: z.ZodType<PublishView> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  tagCategories: z.array(z.lazy(() => PublishViewTagCategory$zodSchema))
    .optional(),
});
