/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TopicBreadcrumb,
  TopicBreadcrumb$zodSchema,
} from "./topicbreadcrumb.js";

/**
 * Format of the source document (HTML, Doc, or PDF).
 */
export const ReferenceResponseDocType$zodSchema = z.enum([
  "HTML",
  "Doc",
  "PDF",
]).describe("Format of the source document (HTML, Doc, or PDF).");

export type ReferenceResponseDocType = z.infer<
  typeof ReferenceResponseDocType$zodSchema
>;

/**
 * Source Type
 */
export const ReferenceResponseSource$zodSchema = z.enum([
  "eGain Article",
  "eGain Attachment",
]).describe("Source Type");

export type ReferenceResponseSource = z.infer<
  typeof ReferenceResponseSource$zodSchema
>;

/**
 * One document used in generated response
 */
export type ReferenceResponse = {
  id: string;
  name: string;
  docType: ReferenceResponseDocType;
  source: ReferenceResponseSource;
  topicBreadCrumb?: TopicBreadcrumb | undefined;
};

export const ReferenceResponse$zodSchema: z.ZodType<
  ReferenceResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  docType: ReferenceResponseDocType$zodSchema,
  id: z.string(),
  name: z.string(),
  source: ReferenceResponseSource$zodSchema,
  topicBreadCrumb: TopicBreadcrumb$zodSchema.optional(),
}).describe("One document used in generated response");
