/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4ab56b57ba20
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  AITopicBreadcrumb,
  AITopicBreadcrumb$zodSchema,
} from "./aitopicbreadcrumb.js";

/**
 * Format of the source document (HTML, DOCX, PPTX, or PDF).
 */
export const ReferenceResponseDocType = {
  Html: "HTML",
  Docx: "DOCX",
  Pdf: "PDF",
  Pptx: "PPTX",
} as const;
/**
 * Format of the source document (HTML, DOCX, PPTX, or PDF).
 */
export type ReferenceResponseDocType = ClosedEnum<
  typeof ReferenceResponseDocType
>;

export const ReferenceResponseDocType$zodSchema = z.enum([
  "HTML",
  "DOCX",
  "PDF",
  "PPTX",
]).describe("Format of the source document (HTML, DOCX, PPTX, or PDF).");

/**
 * Source Type
 */
export const ReferenceResponseSource = {
  EGainArticle: "eGain Article",
  EGainAttachment: "eGain Attachment",
} as const;
/**
 * Source Type
 */
export type ReferenceResponseSource = ClosedEnum<
  typeof ReferenceResponseSource
>;

export const ReferenceResponseSource$zodSchema = z.enum([
  "eGain Article",
  "eGain Attachment",
]).describe("Source Type");

/**
 * One document used in generated response
 */
export type ReferenceResponse = {
  id: string;
  name: string;
  docName?: string | undefined;
  docType: ReferenceResponseDocType;
  source: ReferenceResponseSource;
  topicBreadcrumb?: Array<AITopicBreadcrumb> | undefined;
};

export const ReferenceResponse$zodSchema: z.ZodType<ReferenceResponse> = z
  .object({
    docName: z.string().optional(),
    docType: ReferenceResponseDocType$zodSchema,
    id: z.string(),
    name: z.string(),
    source: ReferenceResponseSource$zodSchema,
    topicBreadcrumb: z.array(AITopicBreadcrumb$zodSchema).optional(),
  }).describe("One document used in generated response");
