/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  RequiredLanguageCode,
  RequiredLanguageCode$zodSchema,
} from "./requiredlanguagecode.js";
import {
  RetrieveRequest,
  RetrieveRequest$zodSchema,
} from "./retrieverequest.js";
import {
  RetrieveResponse,
  RetrieveResponse$zodSchema,
} from "./retrieveresponse.js";

export type RetrieveChunksRequest = {
  q: string;
  portalID: string;
  dollarFilterUserProfileID?: string | undefined;
  Dollar_lang: RequiredLanguageCode;
  dollarFilterTags?: { [k: string]: Array<string> } | undefined;
  dollarFilterTopicIds?: Array<string> | undefined;
  RetrieveRequest?: RetrieveRequest | undefined;
};

export const RetrieveChunksRequest$zodSchema: z.ZodType<
  RetrieveChunksRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  Dollar_lang: RequiredLanguageCode$zodSchema,
  RetrieveRequest: RetrieveRequest$zodSchema.optional(),
  dollarFilterTags: z.record(z.array(z.string())).describe(
    "An object where each key is a **Category Tag ID** (numeric string),  \n"
      + "and each value is an array of **Tag IDs** for that category.\n"
      + " **Note**:\n"
      + "  - The '$filter[tags]' query parameter JSON value should be url encoded.\n"
      + "  - Some developer tools for invoking APIs may not url encode the '$filter[tags]' query parameter JSON value by default. Ensure that only url encoded values are used.\n"
      + "  - Example of JSON value: {\"BASE-40845\":[\"BASE-40849\",\"BASE-40853\"]}\n"
      + "  - Example of URL encoded value: %7B%22BASE-40845%22%3A%5B%22BASE-40849%22%2C%22BASE-40853%22%5D%7D\n"
      + "",
  ).optional(),
  dollarFilterTopicIds: z.array(z.string()).describe(
    "An array of topic IDs. It is used to restrict search results to specific topics.",
  ).optional(),
  dollarFilterUserProfileID: z.string().optional(),
  portalID: z.string().describe(
    "The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.",
  ),
  q: z.string().describe("The search query string."),
});

export type RetrieveChunksResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  RetrieveResponse?: RetrieveResponse | undefined;
};

export const RetrieveChunksResponse$zodSchema: z.ZodType<
  RetrieveChunksResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  RetrieveResponse: RetrieveResponse$zodSchema.optional(),
  StatusCode: z.number().int(),
});
