/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type SchemasTags = {
  id?: string | undefined;
  tags?: Array<string> | undefined;
};

export const SchemasTags$zodSchema: z.ZodType<
  SchemasTags,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  tags: z.array(z.string()).optional(),
});
