/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type SchemasLink = {
  rel?: string | undefined;
  href?: string | undefined;
  _default?: boolean | undefined;
};

export const SchemasLink$zodSchema: z.ZodType<
  SchemasLink,
  z.ZodTypeDef,
  unknown
> = z.object({
  _default: z.boolean().optional(),
  href: z.string().optional(),
  rel: z.string().optional(),
});
