/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 15cdea66db1a
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  AITopicBreadcrumb,
  AITopicBreadcrumb$zodSchema,
} from "./aitopicbreadcrumb.js";

/**
 * Format of the source document (HTML, DOCX, PPTX, or PDF).
 */
export const SearchResultDocType = {
  Html: "HTML",
  Docx: "DOCX",
  Pdf: "PDF",
  Pptx: "PPTX",
} as const;
/**
 * Format of the source document (HTML, DOCX, PPTX, or PDF).
 */
export type SearchResultDocType = ClosedEnum<typeof SearchResultDocType>;

export const SearchResultDocType$zodSchema = z.enum([
  "HTML",
  "DOCX",
  "PDF",
  "PPTX",
]).describe("Format of the source document (HTML, DOCX, PPTX, or PDF).");

/**
 * The repository or system where the content originated (e.g., eGain Article, eGain Attachment).
 */
export const SearchResultSource = {
  EGainArticle: "eGain Article",
  EGainAttachment: "eGain Attachment",
} as const;
/**
 * The repository or system where the content originated (e.g., eGain Article, eGain Attachment).
 */
export type SearchResultSource = ClosedEnum<typeof SearchResultSource>;

export const SearchResultSource$zodSchema = z.enum([
  "eGain Article",
  "eGain Attachment",
]).describe(
  "The repository or system where the content originated (e.g., eGain Article, eGain Attachment).",
);

export const SnippetType = {
  Chunks: "chunks",
  ArticleContent: "articleContent",
} as const;
export type SnippetType = ClosedEnum<typeof SnippetType>;

export const SnippetType$zodSchema = z.enum([
  "chunks",
  "articleContent",
]);

/**
 * Represents a single document or snippet returned by search, along with its metadata and relevance score.
 */
export type SearchResult = {
  id: string;
  name: string;
  docName?: string | undefined;
  docType: SearchResultDocType;
  source: SearchResultSource;
  snippet: string;
  contextualSummary?: string | undefined;
  snippetType?: SnippetType | undefined;
  relevanceScore?: number | undefined;
  normalizedScore?: number | undefined;
  topicBreadcrumb?: Array<AITopicBreadcrumb> | undefined;
};

export const SearchResult$zodSchema: z.ZodType<SearchResult> = z.object({
  contextualSummary: z.string().optional(),
  docName: z.string().optional(),
  docType: SearchResultDocType$zodSchema,
  id: z.string(),
  name: z.string(),
  normalizedScore: z.number().optional(),
  relevanceScore: z.number().optional(),
  snippet: z.string(),
  snippetType: SnippetType$zodSchema.optional(),
  source: SearchResultSource$zodSchema,
  topicBreadcrumb: z.array(AITopicBreadcrumb$zodSchema).optional(),
}).describe(
  "Represents a single document or snippet returned by search, along with its metadata and relevance score.",
);
