/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AITopicBreadcrumb,
  AITopicBreadcrumb$zodSchema,
} from "./aitopicbreadcrumb.js";

/**
 * Format of the source document (HTML, DOCX, PPTX, or PDF).
 */
export const SearchResultDocType$zodSchema = z.enum([
  "HTML",
  "DOCX",
  "PDF",
  "PPTX",
]).describe("Format of the source document (HTML, DOCX, PPTX, or PDF).");

export type SearchResultDocType = z.infer<typeof SearchResultDocType$zodSchema>;

/**
 * The repository or system where the content originated (e.g., eGain Article, eGain Attachment).
 */
export const SearchResultSource$zodSchema = z.enum([
  "eGain Article",
  "eGain Attachment",
]).describe(
  "The repository or system where the content originated (e.g., eGain Article, eGain Attachment).",
);

export type SearchResultSource = z.infer<typeof SearchResultSource$zodSchema>;

/**
 * Represents a single document or snippet returned by search, along with its metadata and relevance score.
 */
export type SearchResult = {
  id: string;
  name: string;
  docName?: string | undefined;
  docType: SearchResultDocType;
  source: SearchResultSource;
  snippet: string;
  contextualSummary?: string | undefined;
  relevanceScore?: number | undefined;
  normalizedScore?: number | undefined;
  topicBreadcrumb?: Array<AITopicBreadcrumb> | undefined;
};

export const SearchResult$zodSchema: z.ZodType<
  SearchResult,
  z.ZodTypeDef,
  unknown
> = z.object({
  contextualSummary: z.string().optional(),
  docName: z.string().optional(),
  docType: SearchResultDocType$zodSchema,
  id: z.string(),
  name: z.string(),
  normalizedScore: z.number().optional(),
  relevanceScore: z.number().optional(),
  snippet: z.string(),
  source: SearchResultSource$zodSchema,
  topicBreadcrumb: z.array(AITopicBreadcrumb$zodSchema).optional(),
}).describe(
  "Represents a single document or snippet returned by search, along with its metadata and relevance score.",
);
