/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ArticleSearchResult,
  ArticleSearchResult$zodSchema,
} from "./articlesearchresult.js";

/**
 * Top search results with relevance scores
 */
export type SearchResults = {
  article?: Array<ArticleSearchResult> | undefined;
};

export const SearchResults$zodSchema: z.ZodType<
  SearchResults,
  z.ZodTypeDef,
  unknown
> = z.object({
  article: z.array(ArticleSearchResult$zodSchema).optional(),
}).describe("Top search results with relevance scores");

export type SearchResponse = { searchResults: SearchResults };

export const SearchResponse$zodSchema: z.ZodType<
  SearchResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  searchResults: z.lazy(() => SearchResults$zodSchema),
});
