/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Security = { accessToken: string };

export const Security$zodSchema: z.ZodType<Security, z.ZodTypeDef, unknown> = z
  .object({
    accessToken: z.string().describe(
      "JWT Bearer Token authentication for API access",
    ),
  });
