/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ShortURL = {
  id?: string | undefined;
  templateName?: string | undefined;
  shortURLName?: string | undefined;
  isDefault?: boolean | undefined;
};

export const ShortURL$zodSchema: z.ZodType<ShortURL, z.ZodTypeDef, unknown> = z
  .object({
    id: z.string().optional(),
    isDefault: z.boolean().optional(),
    shortURLName: z.string().optional(),
    templateName: z.string().optional(),
  });
