/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ba75809ea890
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const SortIdNameDepartment = {
  Id: "id",
  Name: "name",
  DepartmentName: "departmentName",
} as const;
export type SortIdNameDepartment = ClosedEnum<typeof SortIdNameDepartment>;

export const SortIdNameDepartment$zodSchema = z.enum([
  "id",
  "name",
  "departmentName",
]);
