/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const SortIdNameDepartment$zodSchema = z.enum([
  "id",
  "name",
  "departmentName",
]);

export type SortIdNameDepartment = z.infer<
  typeof SortIdNameDepartment$zodSchema
>;
