/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Milestone, Milestone$zodSchema } from "./milestone.js";

/**
 * A stage in the Article's workflow.
 */
export type Stage = {
  name?: string | undefined;
  milestone?: Milestone | undefined;
};

export const Stage$zodSchema: z.ZodType<Stage, z.ZodTypeDef, unknown> = z
  .object({
    milestone: Milestone$zodSchema.optional(),
    name: z.string().optional(),
  }).describe("A stage in the Article's workflow.");
