/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { L10NString, L10NString$zodSchema } from "./l10nstring.js";

export type StructuredAuthoringFields = {
  confidenceLevel?: L10NString | undefined;
  issue?: string | undefined;
  environment?: string | undefined;
  cause?: string | undefined;
};

export const StructuredAuthoringFields$zodSchema: z.ZodType<
  StructuredAuthoringFields,
  z.ZodTypeDef,
  unknown
> = z.object({
  cause: z.string().optional(),
  confidenceLevel: L10NString$zodSchema.optional(),
  environment: z.string().optional(),
  issue: z.string().optional(),
});
