/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7e9eb633ae53
 */

import * as z from "zod";

export type Tag = { name?: string | undefined; id?: string | undefined };

export const Tag$zodSchema: z.ZodType<Tag> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
});
