/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { TagGroups, TagGroups$zodSchema } from "./taggroups.js";
import { Tags, Tags$zodSchema } from "./tags.js";

/**
 * A tag category is a grouping of tags and tag groups.
 */
export type TagCategory = {
  name?: string | undefined;
  id?: string | undefined;
  tags?: Tags | undefined;
  tagGroups?: TagGroups | undefined;
};

export const TagCategory$zodSchema: z.ZodType<
  TagCategory,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  tagGroups: TagGroups$zodSchema.optional(),
  tags: Tags$zodSchema.optional(),
}).describe("A tag category is a grouping of tags and tag groups.");
