/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1d4628e42dd5
 */

import * as z from "zod";
import { TagGroup, TagGroup$zodSchema } from "./taggroup.js";

export type TagGroups = { tagGroup?: Array<TagGroup> | undefined };

export const TagGroups$zodSchema: z.ZodType<TagGroups> = z.object({
  tagGroup: z.array(TagGroup$zodSchema).optional(),
});
