/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TagGroup = { name?: string | undefined; id?: string | undefined };

export const TagGroup$zodSchema: z.ZodType<TagGroup, z.ZodTypeDef, unknown> = z
  .object({
    id: z.string().optional(),
    name: z.string().optional(),
  });
