/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { TagGroup, TagGroup$zodSchema } from "./taggroup.js";

export type TagGroups = { tagGroup?: Array<TagGroup> | undefined };

export const TagGroups$zodSchema: z.ZodType<TagGroups, z.ZodTypeDef, unknown> =
  z.object({
    tagGroup: z.array(TagGroup$zodSchema).optional(),
  });
