/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Tags = {
  id?: string | undefined;
  tags?: Array<string> | undefined;
};

export const Tags$zodSchema: z.ZodType<Tags, z.ZodTypeDef, unknown> = z.object({
  id: z.string().optional(),
  tags: z.array(z.string()).optional(),
});
