/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1ea0c87bb112
 */

import * as z from "zod";
import { Tag, Tag$zodSchema } from "./tag.js";

export type Tags = { tag?: Array<Tag> | undefined };

export const Tags$zodSchema: z.ZodType<Tags> = z.object({
  tag: z.array(Tag$zodSchema).optional(),
});
