/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { TopicSummary, TopicSummary$zodSchema } from "./topicsummary.js";

/**
 * This schema contains one or more TopicSummary instances.
 */
export type TopicBreadcrumb = {
  topicSummary?: Array<TopicSummary> | undefined;
};

export const TopicBreadcrumb$zodSchema: z.ZodType<
  TopicBreadcrumb,
  z.ZodTypeDef,
  unknown
> = z.object({
  topicSummary: z.array(TopicSummary$zodSchema).optional(),
}).describe("This schema contains one or more TopicSummary instances.");
