/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Stage, Stage$zodSchema } from "./stage.js";

/**
 * The Article's workflow.
 */
export type Workflow = { stages?: Array<Stage> | undefined };

export const Workflow$zodSchema: z.ZodType<Workflow, z.ZodTypeDef, unknown> = z
  .object({
    stages: z.array(Stage$zodSchema).optional(),
  }).describe("The Article's workflow.");
