/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e000cee3c0e0
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const WorkflowMilestone = {
  Authoring: "authoring",
  Staging: "staging",
  Publish: "publish",
} as const;
export type WorkflowMilestone = ClosedEnum<typeof WorkflowMilestone>;

export const WorkflowMilestone$zodSchema = z.enum([
  "authoring",
  "staging",
  "publish",
]);
