/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const WorkflowMilestone$zodSchema = z.enum([
  "authoring",
  "staging",
  "publish",
]);

export type WorkflowMilestone = z.infer<typeof WorkflowMilestone$zodSchema>;
