/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8aade1e241a0
 */

import * as z from "zod";
import { Stage, Stage$zodSchema } from "./stage.js";

/**
 * The Article's workflow.
 */
export type Workflow = { stages?: Array<Stage> | undefined };

export const Workflow$zodSchema: z.ZodType<Workflow> = z.object({
  stages: z.array(Stage$zodSchema).optional(),
}).describe("The Article's workflow.");
